version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgresMovieReview
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    env_file:
      - ./app.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # restart: unless- stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadminMovieReview
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    env_file:
      - ./app.env
    ports:
      - "5050:80"
    depends_on:
      - postgres
    # restart: unless-stopped

  # gorm:
  #   image: gorm
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   environment: 
  #     DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydatabase?sslmode=disable&TimeZone=Asia/Bankok
    # ports:
    #   - 8080:8080

volumes:
  postgres_data: