
services:
  webmoviereview:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: air cmd/main.go -b 0.0.0.0
    depends_on:
      postgres:
        condition: service_healthy
      pgadmin:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - movieReviewNetwork

  postgres:
    image: postgres:latest
    container_name: PGMovieReviewAPP1
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5435"
    restart: unless-stopped
    networks:
      - movieReviewNetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: PGAMovieReviewAPP1
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASSWORD}
    ports:
      - "5055:85"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - movieReviewNetwork
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:

networks:
  movieReviewNetwork:
    driver: bridge





# version: '3.8'

# services:
#   postgres:
#     image: postgres:latest
#     container_name: postgresMovieReview
#     environment:
#       POSTGRES_DB: mydatabase
#       POSTGRES_USER: myuser
#       POSTGRES_PASSWORD: mypassword
#     # env_file:
#     #   - ./app.env
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
#     # restart: unless- stopped

#   pgadmin:
#     image: dpage/pgadmin4:latest
#     container_name: pgadminMovieReview
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@admin.com
#       PGADMIN_DEFAULT_PASSWORD: admin
#     # env_file:
#     #   - ./app.env
#     ports:
#       - "5050:80"
#     depends_on:
#       - postgres
#     # restart: unless-stopped

# volumes:
#   postgres_data:
